#Part - 1 : Tensorflow 

In [2]:
import tensorflow as tf

In [3]:
print(tf.add(1, 2))
print(tf.add([1, 2], [3, 4]))
print(tf.square(2) + tf.square(3)) 

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(13, shape=(), dtype=int32)


In [7]:
x = tf.matmul([[1],[3]], [[2, 3]])
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor(
[[2 3]
 [6 9]], shape=(2, 2), dtype=int32)
(2, 2)
<dtype: 'int32'>


In [29]:
import numpy as np


print("Implicit conversion of numpy to tensorflow", tf.multiply(np.ones([7,7]), 1))

tensor = tf.multiply(np.ones(7), 7)
print("\nImplicit converserison of tensor to numpy: ",type(np.add(tensor, 1)))

print("The .numpy() method explicitly converts a Tensor to a numpy array", type(tensor.numpy()))

Implicit conversion of numpy to tensorflow tf.Tensor(
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]], shape=(7, 7), dtype=float64)

Implicit converserison of tensor to numpy:  <class 'numpy.ndarray'>
The .numpy() method explicitly converts a Tensor to a numpy array <class 'numpy.ndarray'>


Einsum Operations:

In [22]:
m0 = tf.random.normal(shape=[4, 3])
m1 = tf.random.normal(shape=[3, 6])
e = tf.einsum('ij,jk->ik', m0, m1)
print(e.shape)

(4, 6)


In [23]:
u = tf.random.normal(shape=[5])
v = tf.random.normal(shape=[5])
e = tf.einsum('i,i->', u, v) 
print(e.shape)

()


In [24]:
m = tf.ones(2,3)
e = tf.einsum('ij->ji', m0)
print(e.shape)

(3, 4)


In [19]:
m = tf.reshape(tf.range(9), [3,3])
diag = tf.einsum('ii->i', m)
print(diag.shape)

(3,)


#Part - 2 Pytorch

In [ ]:
import torch
import numpy as np

In [ ]:
data = [[1, 2], [3, 4]]
np_array = np.array(data)
x_data = torch.tensor(data)

In [ ]:
print("The .from_numpy() method explicitly converts a numpy to a tensor array", type(torch.from_numpy(np_array)))
print("The .numpy() method explicitly converts a tensor to a numpy array", type(x_data.numpy()))

print(f"One tensor to another:",torch.ones_like(x_data))

The .from_numpy() method explicitly converts a numpy to a tensor array <class 'torch.Tensor'>
The .numpy() method explicitly converts a tensor to a numpy array <class 'numpy.ndarray'>
One tensor to another: tensor([[1, 1],
        [1, 1]])


In [ ]:
shape = (7,8,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.1568, 0.9591, 0.9281, 0.9728, 0.0264, 0.6206, 0.1651, 0.0591],
        [0.5128, 0.7493, 0.0439, 0.9534, 0.5213, 0.5494, 0.2514, 0.0388],
        [0.4743, 0.3307, 0.2680, 0.7279, 0.9699, 0.3415, 0.1660, 0.6050],
        [0.2828, 0.4466, 0.6015, 0.7886, 0.4404, 0.3498, 0.5910, 0.4759],
        [0.7708, 0.7207, 0.9499, 0.0682, 0.7599, 0.6176, 0.8562, 0.9225],
        [0.7473, 0.5448, 0.7315, 0.1562, 0.6996, 0.9827, 0.2126, 0.5390],
        [0.1041, 0.1564, 0.5323, 0.4284, 0.9244, 0.2267, 0.8299, 0.9503]]) 

Ones Tensor: 
 tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        

In [ ]:
tensor = torch.rand(5, 4)

print(f"Shape of tensor: {x_data.shape}")
print(f"Datatype of tensor: {x_data.dtype}")
print(f"Device tensor is stored on: {x_data.device}")

Shape of tensor: torch.Size([2, 2])
Datatype of tensor: torch.int64
Device tensor is stored on: cpu


In [ ]:
tensor = torch.ones(4, 4)
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor) 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
